// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/Ownable.sol";

interface ICircomVerifier {
    function verifyProof(
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[1] memory input
    ) external view returns (bool r);
}

/**
 * @title GenesisSBT
 * @notice Core Soulbound Token (SBT) contract for Genesis U.S. Citizenship & State Residency verification.
 */
contract GenesisSBT is Ownable {
    ICircomVerifier public immutable zkVerifier;

    struct Identity {
        bool isVerifiedCitizen;
        uint16 stateFips;
        uint256 issueTimestamp;
    }

    // Wallet address => Identity Credential
    mapping(address => Identity) public identityRegistry;
    
    // Nullifier Hash => Claim Status (Prevents duplicate identity claims)
    mapping(uint256 => bool) public nullifiers;

    event SBTClaimed(address indexed holder, uint16 indexed stateFips, uint256 nullifierHash);
    event SBTRevoked(address indexed holder);

    error AlreadyClaimed();
    error NullifierAlreadyUsed();
    error InvalidZKProof();
    error SBTNonTransferable();

    constructor(address _zkVerifierAddress) Ownable(msg.sender) {
        zkVerifier = ICircomVerifier(_zkVerifierAddress);
    }

    /**
     * @notice Claim a Soulbound Identity Credential using a Zero-Knowledge Proof.
     * @param a Groth16 zk-SNARK proof parameter A
     * @param b Groth16 zk-SNARK proof parameter B
     * @param c Groth16 zk-SNARK proof parameter C
     * @param nullifierHash Poseidon hash generated by Circom circuit to prevent re-use
     * @param targetStateFips Public input matching state FIPS code (e.g. 02 for AK)
     */
    function claimSBT(
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint256 nullifierHash,
        uint16 targetStateFips
    ) external {
        if (identityRegistry[msg.sender].isVerifiedCitizen) revert AlreadyClaimed();
        if (nullifiers[nullifierHash]) revert NullifierAlreadyUsed();

        // Prepare public input array for the SnarkJS verifier [targetStateFips]
        uint[1] memory verifierInputs;
        verifierInputs[0] = uint256(targetStateFips);

        // Verify ZK Proof against compiled Circom verifier
        bool valid = zkVerifier.verifyProof(a, b, c, verifierInputs);
        if (!valid) revert InvalidZKProof();

        // Mark nullifier as used permanently
        nullifiers[nullifierHash] = true;

        // Save Soulbound identity record
        identityRegistry[msg.sender] = Identity({
            isVerifiedCitizen: true,
            stateFips: targetStateFips,
            issueTimestamp: block.timestamp
        });

        emit SBTClaimed(msg.sender, targetStateFips, nullifierHash);
    }

    /**
     * @notice External view to check if an account holds a valid Genesis Citizen SBT
     */
    function isVerified(address _account) external view returns (bool, uint16) {
        Identity memory id = identityRegistry[_account];
        return (id.isVerifiedCitizen, id.stateFips);
    }

    /**
     * @notice Emergency administrative revocation of compromised SBT credentials
     */
    function revokeSBT(address _holder) external onlyOwner {
        delete identityRegistry[_holder];
        emit SBTRevoked(_holder);
    }
}
