// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;
interface IWorkerIssuance { function mintWorkerReward(address,uint256) external; }
interface IWorkerOracle { function getDynamicIssuanceRateBps() external view returns(uint256); }
contract WorkerSplit {
    uint256 public constant BPS=10000; uint256 public constant WORKER_RATE_BPS=50; uint256 public constant BOOTSTRAP_POOL=10000 ether; uint64 public constant EPOCH_DURATION=30 days;
    uint8 public constant VALIDATOR=0; uint8 public constant VERIFIER=1; uint8 public constant APP=2; uint8 public constant NOTE=3; uint8 public constant ARBITRATOR=4;
    address public owner; IWorkerIssuance public immutable issuance; IWorkerOracle public immutable oracle; uint64 public epoch=1; uint64 public epochStart; uint256 public rollover; uint256 public activity; bool public bootstrapActive=true;
    mapping(address=>bool) public reporters; mapping(uint8=>address[]) private members; mapping(address=>uint8) public memberKind; mapping(uint64=>mapping(uint8=>uint256)) public pool; mapping(uint64=>mapping(uint8=>mapping(address=>bool))) public claimed; mapping(uint64=>mapping(address=>bool)) public successfulArbitrator;
    event ActivityReported(address indexed reporter,uint256 amount); event EpochFinalized(uint64 indexed epoch,uint256 workerPool); event RewardClaimed(uint64 indexed epoch,uint8 indexed kind,address indexed recipient,uint256 amount);
    modifier onlyOwner(){require(msg.sender==owner,"WorkerSplit: owner");_;} modifier onlyReporter(){require(reporters[msg.sender]||msg.sender==owner,"WorkerSplit: reporter");_;}
    constructor(address issuanceAddress,address oracleAddress){require(issuanceAddress!=address(0)&&oracleAddress!=address(0),"WorkerSplit: zero");owner=msg.sender;issuance=IWorkerIssuance(issuanceAddress);oracle=IWorkerOracle(oracleAddress);epochStart=uint64(block.timestamp);}
    function setReporter(address who,bool enabled) external onlyOwner{reporters[who]=enabled;} function register(uint8 kind) external{require(kind<=ARBITRATOR,"WorkerSplit: kind");require(memberKind[msg.sender]==0&&!(kind==0&&members[0].length>0&&members[0][0]==msg.sender),"WorkerSplit: registered");memberKind[msg.sender]=kind+1;members[kind].push(msg.sender);}
    function recordActivity(uint256 amount) external onlyReporter{activity+=amount;emit ActivityReported(msg.sender,amount);} function recordNativeVolume(uint256 amount) external onlyReporter{activity+=amount;emit ActivityReported(msg.sender,amount);}
    function markSuccessfulArbitrator(uint64 claimEpoch,address arbitrator) external onlyReporter{successfulArbitrator[claimEpoch][arbitrator]=true;if(memberKind[arbitrator]==0){memberKind[arbitrator]=ARBITRATOR+1;members[ARBITRATOR].push(arbitrator);}}
    function finalizeEpoch() external{require(block.timestamp>=epochStart+EPOCH_DURATION,"WorkerSplit: active");uint256 base=activity*WORKER_RATE_BPS/BPS;uint256 dynamic=base*oracle.getDynamicIssuanceRateBps()/100;uint256 workerPool=rollover+dynamic;if(bootstrapActive){workerPool+=BOOTSTRAP_POOL;bootstrapActive=false;}pool[epoch][VALIDATOR]=workerPool*20/100;pool[epoch][VERIFIER]=workerPool*20/100;pool[epoch][APP]=workerPool*30/100;pool[epoch][NOTE]=workerPool*20/100;pool[epoch][ARBITRATOR]=workerPool-pool[epoch][VALIDATOR]-pool[epoch][VERIFIER]-pool[epoch][APP]-pool[epoch][NOTE];rollover=0;emit EpochFinalized(epoch,workerPool);epoch++;epochStart=uint64(block.timestamp);activity=0;}
    function claim(uint64 claimEpoch,uint8 kind) external{require(claimEpoch<epoch&&kind<=ARBITRATOR&&!claimed[claimEpoch][kind][msg.sender],"WorkerSplit: claim");uint256 amount; if(kind==ARBITRATOR){require(successfulArbitrator[claimEpoch][msg.sender],"WorkerSplit: no award");uint256 count=0;for(uint256 i=0;i<members[kind].length;i++)if(successfulArbitrator[claimEpoch][members[kind][i]])count++;require(count>0,"WorkerSplit: no arbitrators");amount=pool[claimEpoch][kind]/count;}else{uint256 count=members[kind].length;require(count>0,"WorkerSplit: no members");amount=pool[claimEpoch][kind]/count;}require(amount>0,"WorkerSplit: empty");claimed[claimEpoch][kind][msg.sender]=true;issuance.mintWorkerReward(msg.sender,amount);emit RewardClaimed(claimEpoch,kind,msg.sender,amount);}
    function participantCount(uint8 kind) external view returns(uint256){return members[kind].length;}
}
